# Generated by Django 5.1.4 on 2024-12-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=100)),
                ('test_number', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('cambridge_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='costumadmin.cambridgetest')),
            ],
        ),
    ]
