# Generated by Django 5.1.4 on 2024-12-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumadmin', '0002_testdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDetail',
        ),
    ]
