# Generated by Django 5.1.4 on 2024-12-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=155, verbose_name='Topic')),
                ('part_type', models.CharField(choices=[('part1', 'Part 1'), ('part2', 'Part 2'), ('part3', 'Part 3'), ('fulltest', 'Full Test')], max_length=10, verbose_name='Part Type')),
            ],
        ),
        migrations.CreateModel(
            name='Part1Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('part_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user.parttopic')),
            ],
        ),
    ]
