# Generated by Django 5.1.4 on 2024-12-31 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part1question',
            name='part_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part1_questions', to='user.parttopic'),
        ),
        migrations.CreateModel(
            name='Part2Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Cue Card Question')),
                ('hint1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hint 1')),
                ('hint2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hint 2')),
                ('hint3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hint 3')),
                ('part_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part2_questions', to='user.parttopic')),
            ],
        ),
        migrations.CreateModel(
            name='Part3Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Discussion Question')),
                ('follow_up_question', models.CharField(blank=True, max_length=255, null=True, verbose_name='Follow-Up Question')),
                ('part_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part3_questions', to='user.parttopic')),
            ],
        ),
    ]
